### ISSUE TITLE
include tutorial

### ISSUE THREAD

**Issue by hyperknot** [sevanspowell/MetalDeferredLightingTutorial#1]
Since the tutorial seems to be down, can you possibly include it in a folder as markdown so we can read it on GitHub?

**Comment by sevanspowell** [comment]
Sorry about that!

I'll be working on getting the tutorial back up but I've also uploaded it into the doc/ folder:

https://github.com/sevanspowell/MetalDeferredLightingTutorial/blob/master/doc/implementing-deferred-shading-in-metal.md

Thanks for letting me know!
